Express.js CDK
last9/last9-cdk pull request #22
Opened 2023-07-03 06:08 UTC by chtushar

2023-07-04 05:33 UTC, anik3tra0 requested changes

2023-07-04 05:33 UTC, anik3tra0 commented on js/express/src/CDK.ts
> +        const parsedPathname = getParsedPathname(req.url ?? "/", undefined);
@chtushar can we use req.path instead of req.url. This just gives the path minus query params or anything extra.

2023-07-04 06:13 UTC, anik3tra0 approved these changes

2023-07-14 07:53 UTC, prathamesh-sonpatki approved these changes

2023-07-14 07:53 UTC, merged